### ISSUE TITLE
No tagged release with typo fix

### ISSUE THREAD

**Issue by geekish** [paragonie/anti-csrf#16]
I had to change the version constraint in my project's composer.json from `^2.0` to `dev-master` in order to use this library because of the typo fixed in #13.

It would be lovely if you could tag a release, as I prefer not to use dev-master if I don't have to. :)

**Comment by hansott** [comment]
Bump

**Comment by paragonie-scott** [comment]
Somehow, the email notifications for this repo aren't showing up in the usual place. I'll have to check my filters.

https://github.com/paragonie/anti-csrf/releases/tag/v2.0.1
