### ISSUE TITLE
Fatal PHP error thrown when using reconfigure()

### ISSUE THREAD

**Issue by antonyakushin** [paragonie/anti-csrf#17]
Unable to use the reconfigure() function at all. Any array passed throws "PHP Fatal error:  Uncaught Error: Cannot access empty property". I believe the cause of this is in AntiCSRF.php:

`$this->${$opt} = $val;`

should be changed to:

`$this->${opt} = $val;` or `$this->$opt = $val;`

As `$this->${$opt}` where $opt = 'expire_old', for example, gets parsed as `$this->$expire_old` instead of `$this->expire_old`.

**Comment by paragonie-scott** [comment]
Oh, I think this is closable now with #18 merged?
