### ISSUE TITLE
Current release breaks PATH_INFO as lock

### ISSUE THREAD

**Issue by acornforth** [paragonie/anti-csrf#28]
In the function validateRequestNative(), the path lock is checking against REQUEST_URI (hardcoded), this negates the feature added in #20 when $useNativeSession gets set to true....
this could be easily fixed in-place but the function has already been refactored and the bug looks like it's fixed in the dev branch, for now i've just reverted back to the my forked repo while we wait for a fresh stable release please :)

**Comment by harikt** [comment]
May be close the issue for #20 is merged ?

**Comment by acornforth** [comment]
@harikt yes #20 is merged, but another commit since then break the functionality, this is where we are with the current release...
yet another commit since then fixes the issue, but those more recent changes though merged, haven't made it into the release yet.... all i'm asking for here is another release to made from the code in the dev branch as soon as is practical.
